### ISSUE TITLE
Your scripts work in windows?

### ISSUE THREAD

**Issue by Havokdan** [OmegaPhil/kvirc-xdcc-bot-stats-script#2]
Because I tried all your scripts in windows 8.1 and only worked "Leeching Script" and "Peak users script", all other, an error message. Thank you and have a nice day.

**Comment by OmegaPhil** [comment]
In the help (F1), HelpIndex tab, do you have the 'dialog class' article?

**Comment by OmegaPhil** [comment]
d00p has confirmed the help is there at least. It appears to be something wrong with the build, apparently its refusing to load modules\kviobjects.dll.

**Comment by OmegaPhil** [comment]
Right, there was a bugger up in the linking phase of the build - was missing some libraries, the latest build has this fixed - please can you install and retest.

**Comment by Havokdan** [comment]
I'll try again, once you have the answer I give you the return. I am also facing other problems with these builds, they are giving many crashes.

**Comment by OmegaPhil** [comment]
OK - I'll keep this open for as long as needed - please talk with d00p on #kvirc on Freenode about the build issues (and just ask in the chan in general), but it sounds like he won't be able to give you much support (he doesn't use the builds himself, hes GNU/Linux like me). You can use chatzilla in Firefox etc to get at IRC capability when KVIrc is screwing up e.g.

**Comment by Havokdan** [comment]
Their scripts are working well, thank you, now we have problems with the build of d00p. In general the program gives crash when trying to connect to some servers and when I try to close the application, but this is already the Kvirc. Thank you, stay with god.

**Comment by OmegaPhil** [comment]
OK, I will resolve - I do recommend turning up at #kvirc and making yourself known - your bug here has kicked things into action, and there probably arent many people actually using (and therefore testing) the build.

**Comment by Havokdan** [comment]
I'm already on freenode, but not using the kvirc, due to the crash.
