### ISSUE TITLE
Your scripts do not work in the past builds ....

### ISSUE THREAD

**Issue by Havokdan** [OmegaPhil/kvirc-xdcc-bot-stats-script#4]
His scripts stopped working in recent builds I get in "http://kvirc.d00p.de" it seems that something has changed in recent builds and most no longer works, except "XDCC leeching", all other non-work.
I'm using Windows 10 Pro x64 and x64 KVirc the aforementioned site.

Thank you and have a nice day.

Note: Do not mastered the English language, I use google translator, sorry.

**Comment by OmegaPhil** [comment]
I'm successfully running KVIrc built with 29.08.15 sources currently (git-5230-g19fe0a1), thats pretty recent - what version are you running? Help -> About KVIrc -> Executable Information tab: Build Date, Revision Number.

**Comment by Havokdan** [comment]
KVIrc 4.3.2 'Aria'

Informação de execução:
Sistema: Windows Release : 6.2.9200
Versão do Sistema: Windows 8 Professional (x64) (Build 9200)
Arquitectura: Intel64 Family 6 Model 58 Stepping 9

Informação de Compilação:
Data de Compilação: 2015-09-07 02:34:27 UTC
Data das Fontes: 20141230
Revisão: git-5283-g14adfc5
Sistema: Windows-6.2
CPU: AMD64
Comando de Compilação: C:/Program Files (x86)/CMake/bin/cmake.exe
Opções de Compilação: 
   MANDIR=share/man
   CMAKE_INSTALL_PREFIX=C:/projects/kvirc/build/release
   Threads=Win32
Compilador: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/cl.exe
Opções do Compilador: /DWIN32 /D_WINDOWS /W3 /GR /EHsc

**Comment by OmegaPhil** [comment]
Can you report this in the KVIrc bug tracker, they've recently moved to github as well: https://github.com/kvirc/KVIrc/issues

I bet you're the only one using these builds at the moment... you need to get some sort of error for them though, e.g. when you try to use one of my scripts, does something appear in the active server console/server window?

**Comment by OmegaPhil** [comment]
I've confirmed that these builds aren't really being tested, they're simply built and hosted...

**Comment by Havokdan** [comment]
Well, I just wanted to make you aware of the problem.

**Comment by OmegaPhil** [comment]
OK, in general I am not interested in Windows failures (the one exception would be if I used a platform-specific path when there was no need to be so specific).

**Comment by OmegaPhil** [comment]
For reference I've just upgraded to git-5289-g0e9ae5d, scripts are working fine here under a normal GNU/Linux build.

**Comment by Havokdan** [comment]
Well, until I try to use KVirc in Windows, but the scripts for mIRC made me dependent on him, I can not be without the resources of Invision script and XDCC Killper. Not to mention the constant crashs, although these latest builds the crash that occurred suddenly and stopped when leaving, now crashs occur only when I am editing the issues, whether changing a font or color of a particular item, but I'll keep an eye. Thank you and have a nice day.

**Comment by OmegaPhil** [comment]
I'm closing this as invalid now - I empathise with the shit situation you have with the Windows build of KVIrc, but you need to report this on the KVIrc issue tracker (it won't be anything to do with my scripts, you have some much more serious issues there).
